# -*- coding: utf-8 -*-  
import pygame,copy,math,os
from cubeGlobal import background,screen,green,bright_green,gray,colors,getDisplayParams
from cubeCommon import button
import cubeView,cubeModel


class CubeSnapshot:
    def __init__(self,cube,width, height, fov, distance,x_adj,y_adj):
        self.total =  0
        self.total_page = 0
        self.current = -1
        self.current_page = -1
        self.next_index = 0
        self.snapshots = []
        self.x_adj = x_adj
        self.y_adj = y_adj
        self.width = width
        self.height = height
        self.fov = fov
        self.distance = distance
        self.sn_cube_3d = cubeView.Cube3D(cube,width, height, fov, distance, x_adj,y_adj)

        try:
            with open(".\\snapshots\\index", "r",1) as fo:
                for line in fo.readlines():
                    b = line.strip("(\n)").split(" ")
                    if b[0] != "" and b[0][0] != "#":
                        self.snapshots.append(b[0])
        except IOError as err:  
            fo = open(".\\snapshots\\index", "w", 1)
            fo.write("#generated by this program, never modify it.\n")
            fo.close()   
        if len(self.snapshots) > 0:
            self.setTotal(len(self.snapshots))
            self.setCurrent(1)		
            last = self.snapshots[-1]
            last_index = int(last[7:-4])
            self.next_index = last_index
			

    def saveCube(self,cube,flag):
        if flag == 0:
            fo = open(".\\mycube.clp", "w", 1)
        else:
            self.next_index += 1
            new_sn = "mycube_" + str(self.next_index) + ".clp"
            fs = open(".\\snapshots\\index", "a", 1)
            fs.write(new_sn + "\n")
            fs.close()
            self.setTotal(self.total + 1)
            self.snapshots.append(new_sn)
            fo = open(".\\snapshots\\mycube_" + str(self.next_index) + ".clp", "w", 1)
            self.takeSnapshot(cube)
            self.setCurrent(self.getTotal())
        fo.write("(defrule start-up =>\n")
        for block in cube.blocks:
            block_str = "(assert (blk %d %d %d %c %c %c))\n" % (block.current.x, block.current.y, block.current.z,
              block.colors[0],block.colors[1],block.colors[2])
            fo.write(block_str)
        fo.write("\n(assert (phase 0)))")
        fo.close()
			

    def deleteSnapshot(self,dumy):        
        if self.total == 0 or self.current == 0:
            return
        os.remove(".\\snapshots\\" + self.snapshots[self.current-1])
        del(self.snapshots[self.current-1])
        with open(".\\snapshots\\index", "w", 1) as fo:
            fo.write("#generated by this program, never modify it.\n")
            for line in self.snapshots:
                fo.write(line + "\n")
        self.setTotal(self.total - 1)
        if self.current > 0:
            self.setCurrent(self.current - 1)
        if self.current == 0:
            self.setCurrent(self.current + 1)
        self.selectSnapshot(self.current)
		
    def selectSnapshot(self,b):        
        if self.total == 0:
            return		
        self.current = b
        fo = open(".\\snapshots\\" + self.snapshots[b-1], "r", 1)
        blocks = []
        if fo != None:
            for line in fo.readlines():
                b = line.strip("(\n)").split(" ")
                if b[0] == "assert" and b[1] == "(blk":
                    blocks.append(((int(b[2]),int(b[3]),int(b[4])),"".join([b[5],b[6],b[7]])))
            fo.close()
            cube = cubeModel.Cube(blocks)
            self.sn_cube_3d = cubeView.Cube3D(cube,self.width, self.height, self.fov, 
                self.distance,self.x_adj,self.y_adj)
            self.sn_cube_3d.buildFaces()
            self.displayCube()
			
    def setCurrent(self,c):
        if self.total == 0:
            return		
        self.current = c
        m,r = divmod(c,10)
        if (m + r) != 0:
            if r == 0:
                self.current_page = m
            else:
                self.current_page = m + 1        
		
    
    def setTotal(self,t):        
        self.total = t
        m,r = divmod(t,10)
        if (m + r) != 0:
            if r == 0:
                self.total_page = m
            else:
                self.total_page = m + 1
				
    def getTotal(self):        
        return self.total 
		
    def nextPage(self,flag):
        if self.current_page < self.total_page:
            self.current_page += 1
    def prevPage(self,flag):
        if self.current_page > 0:
            self.current_page -= 1
            
    def displayHeader(self):
        screen,ft_sz,x_scale,y_scale= getDisplayParams()
        b_x = x_scale*810
        b_y = y_scale*10
        b_h = y_scale*30
        if self.total_page == 0:
            start = 0
            stop1 = 0
            stop2 = 10        
        else:
            start = (self.current_page -1)*10
            stop1 = start + 10
            stop2 = stop1        
            if self.current_page == self.total_page:
                stop1 = self.total
        if self.current_page == 1:
            button(screen, "<<", ft_sz, b_x, b_y, x_scale*30,b_h,gray,bright_green,None,-1)
        else:
            button(screen, "<<", ft_sz, b_x, b_y, x_scale*30,b_h,green,bright_green,self.prevPage,-1)
        b_x += x_scale*40

        for b in range(start,stop1):
            if (b + 1) == self.current:		
                button(screen, str(b+1), ft_sz, b_x, b_y, x_scale*30,b_h,bright_green,bright_green,self.selectSnapshot,b+1)
            else:
                button(screen, str(b+1), ft_sz, b_x, b_y, x_scale*30,b_h,green,bright_green,self.selectSnapshot,b+1)
            b_x += x_scale*40
        for b in range(stop1, stop2):
            button(screen, "", ft_sz, b_x, b_y, x_scale*30,b_h,gray,bright_green,None,b+1)
            b_x += x_scale*40
        if self.current_page == self.total_page:
            button(screen, ">>", ft_sz, b_x, b_y, x_scale*30,b_h,gray,bright_green,None,1)
        else:
            button(screen, ">>", ft_sz, b_x, b_y, x_scale*30,b_h,green,bright_green,self.nextPage,1)
        button(screen, u"删除", ft_sz, x_scale*1280, y_scale*560, x_scale*60,y_scale*30,green,bright_green,self.deleteSnapshot,1)
			
    def takeSnapshot(self,cube):
        self.sn_cube_3d.cube = copy.deepcopy(cube)
        self.sn_cube_3d.buildFaces()
        self.displayCube()
        
    def displayCube(self):   
        screen,ft_sz,x_scale,y_scale= getDisplayParams()
        pygame.draw.rect(screen,background,(x_scale*810,
                y_scale*5,x_scale*538,y_scale*595))    
		
        self.sn_cube_3d.displayCube()
        self.sn_cube_3d.displayLayer("RIGHT",2, 180,-70)
        self.sn_cube_3d.displayLayer("UP",2, 160, 260)
        self.sn_cube_3d.displayLayer("FRONT",2, 480, -70)
